### ISSUE TITLE
Why create new module instead of hooking into the existing?

### ISSUE THREAD

**Issue by beatelite** [rbenhase/ga-event-button#1]
Curious, why did you create an entirely new module vs just hooking into the existing using the existing hook?

```
function my_builder_register_settings_form( $form, $id ) {

    if ( 'button' == $id ) {
       // Modify the Button module's $form config array here.
    }

    return $form; // Must be returned!
}
add_filter( 'fl_builder_register_settings_form', 'my_builder_register_settings_form' , 10, 2);
```

I'm wondering because I plan to use this as inspiration to do exactly that but I'm wondering if you ran into issues with that along the way or just opted against it for other reasons?

With the looming glut of different button mods from other devs, i'm trying to limit how many new modules I introduce to users - hence wanting to hook in vs create new.

**Comment by rbenhase** [comment]
Hi Thomas,

Great question. In this particular case, there were two main reasons: the
desire for client-side validation and overall portability/ease of
management.

While using the fl_builder_register_settings_form filter (along with
fl_builder_render_js) should be able to accomplish most of what I wanted,
there isn't (as far as I know) a way to filter the module's settings.js
file to include additional validation rules (e.g. requiring certain fields
or ensuring that they only accept digits). It seems like such a small thing
to create an entirely new module over, but I considered some basic
client-side validation to be pretty important.

Second, I needed non-developers/non-technical people to be able to install
this across multiple sites; having them create a plugin or edit their
theme's functions.php file was not really an option. I considered
overriding the built-in Button module, as outlined in Beaver Builder's
custom module documentation, but even that would require a certain level of
access/knowledge to install, and it didn't seem like the ideal solution if
it was going to be used on a few dozen websites.

So, instead, I essentially cloned the built-in Button module, added my
Google Analytics functionality on top of that, and released it as a
separate module (all in all, it took less than an hour). It's very much a
"niche" module, but it should be user-friendly for a non-developer to
install. It can be added to a site in one click via Beaver Brewer, and it
can also receive updates (which is pretty useful if, say, Google changed
the way event tracking worked and we had 50 sites that needed updated). It
also keeps the standard button form simpler for people who don't need
Google Analytics event tracking, I suppose.

That said, using the plugin filters that are available in Beaver Builder is
a perfectly acceptable option if it meets your needs (and if you don't have
to worry about, say, project managers adding it to a bunch of sites). Hope
that helps.

**Comment by beatelite** [comment]
Thanks for the detailed response. After considering it for a bit, I agree with the validation bit and am going to take the same tack. Gracias, Senior!
